### ISSUE TITLE
Update VisUI to libGDX 1.9.9

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/vis-ui#275]
* [x] Release 1.4.0 for libGDX 1.9.6
* [ ] Fix #271
* [ ] Release 1.4.1 for libGDX 1.9.8
* [ ] Update setup tools

**Comment by metaphore** [comment]
I believe this should be right to make next release straight to `1.9.8`, because `1.9.7` is quite unstable and should be in rare use after latest release.

**Comment by kotcrab** [comment]
I agree, this was created before `1.9.8`.
 `1.4.0` for `1.9.6` was released. 
`1.4.1-SNAPSHOT` for `1.9.8` should be available in few minutes.

**Comment by CreamyCookie** [comment]
I'm using LibGDX 1.98 and VisUI 1.4.1-SNAPSHOT.. 

Is there any reason why an `InputListener`'s enter (mouse over) and exit wouldn't be triggered? It works on clicking though (focusBorder is drawn).

**Comment by czyzby** [comment]
Update to 1.9.9. Issues after updating:

```java
java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;
	at com.kotcrab.vis.ui.widget.Draggable.attachTo(Draggable.java:136)
	at com.kotcrab.vis.ui.layout.DragPane.doOnAdd(DragPane.java:336)
	at com.kotcrab.vis.ui.layout.DragPane.addActor(DragPane.java:312)
	at com.kotcrab.vis.ui.widget.tabbedpane.TabbedPane.addTab(TabbedPane.java:255)
	at com.kotcrab.vis.ui.widget.tabbedpane.TabbedPane.add(TabbedPane.java:232)
```

```
java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Actor.getListeners()Lcom/badlogic/gdx/utils/Array;
	at com.kotcrab.vis.ui.widget.Tooltip.attach(Tooltip.java:145)
	at com.kotcrab.vis.ui.widget.Tooltip.setTarget(Tooltip.java:168)
```

**Comment by kotcrab** [comment]
`1.4.2-SNAPSHOT` will probably work with `1.9.9`. I'm going to make a proper release this weekend.
